### ISSUE TITLE
During handling of the above exception, another exception occurred:

### ISSUE THREAD

**Issue by IssouLinux** [thewhiteh4t/nexfil#21]
I launch nexfil, it starts then spam this message:

] Finding Profiles...

unhandled exception during asyncio.run() shutdown
task: <Task finished coro=<query() done, defined at ./nexfil.py:165> exception=AttributeError("module 'asyncio' has no attribute 'exceptions'")>
Traceback (most recent call last):
  File "/home/seifer/HackTools/OSINT_Tools/nexfil/modules/string.py", line 9, in test_string
    elif response.status not in codes:
NameError: name 'codes' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./nexfil.py", line 171, in query
    await test_string(session, url, data)
  File "/home/seifer/HackTools/OSINT_Tools/nexfil/modules/string.py", line 17, in test_string
    except asyncio.exceptions.TimeoutError:
AttributeError: module 'asyncio' has no attribute 'exceptions'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/seifer/.pyenv/versions/3.7.13/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/home/seifer/.pyenv/versions/3.7.13/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "./nexfil.py", line 281, in main
    await asyncio.gather(*tasks)
  File "./nexfil.py", line 199, in query
    except asyncio.exceptions.TimeoutError:
AttributeError: module 'asyncio' has no attribute 'exceptions'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./nexfil.py", line 181, in query
    response = await session.head(url, allow_redirects=True)
  File "/home/seifer/.pyenv/versions/3.7.13/lib/python3.7/site-packages/aiohttp/client.py", line 536, in _request
    req, traces=traces, timeout=real_timeout
  File "/home/seifer/.pyenv/versions/3.7.13/lib/python3.7/site-packages/aiohttp/connector.py", line 522, in connect
    raise e
  File "/home/seifer/.pyenv/versions/3.7.13/lib/python3.7/site-packages/aiohttp/connector.py", line 512, in connect
    await fut
concurrent.futures._base.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./nexfil.py", line 199, in query
    except asyncio.exceptions.TimeoutError:
AttributeError: module 'asyncio' has no attribute 'exceptions'
unhandled exception during asyncio.run() shutdown
task: <Task finished coro=<query() done, defined at ./nexfil.py:165> exception=AttributeError("module 'asyncio' has no attribute 'exceptions'")>
Traceback (most recent call last):
  File "/home/seifer/HackTools/OSINT_Tools/nexfil/modules/string.py", line 9, in test_string
    elif response.status not in codes:
NameError: name 'codes' is not defined

**Comment by thewhiteh4t** [comment]
@IssouLinux what is your python version?

**Comment by IssouLinux** [comment]
Python 3.7.13

**Comment by IssouLinux** [comment]
Python 3.7.13

**Comment by thewhiteh4t** [comment]
@IssouLinux upgrade to latest python version

**Comment by IssouLinux** [comment]
It works fine with python 3.8.12, thanks!
